addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.25")
addSbtPlugin("ch.epfl.scala" % "sbt-missinglink" % "0.3.1")
addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "0.8.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.16")
addSbtPlugin("com.timushev.sbt" % "sbt-rewarn" % "0.1.2")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.5")
