// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_api.proto

package com.avast.grpc.jsonbridge.test;

public interface TestApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TestApi)
    com.google.protobuf.MessageOrBuilder {
}
