// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_api.proto

package com.avast.grpc.jsonbridge.test;

public final class TestApiOuterClass {
  private TestApiOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestApi_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestApi_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestApi_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestApi_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestApi_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestApi_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestApi_GetResponse_ResultsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestApi_GetResponse_ResultsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016test_api.proto\"\231\001\n\007TestApi\032\033\n\nGetReque" +
      "st\022\r\n\005names\030\001 \003(\t\032q\n\013GetResponse\0222\n\007resu" +
      "lts\030\001 \003(\0132!.TestApi.GetResponse.ResultsE" +
      "ntry\032.\n\014ResultsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\005:\0028\0012\256\001\n\016TestApiService\0222\n\003Get\022\023" +
      ".TestApi.GetRequest\032\024.TestApi.GetRespons" +
      "e\"\000\0223\n\004Get2\022\023.TestApi.GetRequest\032\024.TestA" +
      "pi.GetResponse\"\000\0223\n\004Get3\022\023.TestApi.GetRe" +
      "quest\032\024.TestApi.GetResponse\"\000B/\n(com.ava" +
      "st.viruslab.authenticator.testapiP\001\210\001\001b\006",
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TestApi_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestApi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestApi_descriptor,
        new String[] { });
    internal_static_TestApi_GetRequest_descriptor =
      internal_static_TestApi_descriptor.getNestedTypes().get(0);
    internal_static_TestApi_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestApi_GetRequest_descriptor,
        new String[] { "Names", });
    internal_static_TestApi_GetResponse_descriptor =
      internal_static_TestApi_descriptor.getNestedTypes().get(1);
    internal_static_TestApi_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestApi_GetResponse_descriptor,
        new String[] { "Results", });
    internal_static_TestApi_GetResponse_ResultsEntry_descriptor =
      internal_static_TestApi_GetResponse_descriptor.getNestedTypes().get(0);
    internal_static_TestApi_GetResponse_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestApi_GetResponse_ResultsEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
